<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="spot">

  <xacro:property name="wheel_radius" value="0.03"/>
  <xacro:property name="wheel_separation" value="0.335"/>
  <xacro:property name="caster_wheel_radius" value="${wheel_radius/2}"/>
  <xacro:property name="caster_wheel_mass" value="0.001"/>
  <xacro:property name="caster_wheel_joint_offset" value="0.3"/>
  <xacro:property name="wheel_offset" value="0.025"/>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}"/> 
    </inertial>
  </xacro:macro>

  <!-- not used currently but maybe can be used for better spot model inertia estimation
    <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m / 12.0 * (d*d + h*h)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (w*w + h*h)}" iyz="0.0" izz="${m / 12.0 * (w*w + d*d)}"/>
    </inertial>
  </xacro:macro> -->

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${2.0*m*(r*r)/5.0}" ixy="0.0" ixz="0.0" iyy="${2.0*m*(r*r)/5.0}" iyz="0.0" izz="${2.0*m*(r*r)/5.0}"/>
    </inertial>
  </xacro:macro>

  <link name="base_footprint">
    <xacro:default_inertial mass="32.5"/>
    <visual name="visual">
      <origin xyz="0 0 .655" rpy="0 0 0" />
      <geometry>
	      <mesh filename="package://spot_description/meshes/spot_whole_body.dae" />     
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 .655" rpy="0 0 0" />
      <geometry>
	      <mesh filename="package://spot_description/meshes/spot_whole_body.dae" />
      </geometry>
    </collision>
  </link>

  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.005"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="0.005"/>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_footprint"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${wheel_offset} ${(wheel_separation/2)*reflect} -0.005" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="left" reflect="0.6"/>
  <xacro:wheel prefix="right" reflect="-0.6"/>

  <xacro:macro name="caster" params="prefix reflectH reflectV">
    <link name="${prefix}_caster_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>
      <xacro:sphere_inertia m="0.05" r="${caster_wheel_radius}"/>
    </link>

    <joint name="${prefix}_caster_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_footprint"/>
      <child link="${prefix}_caster_wheel"/>
      <origin xyz="${wheel_offset + caster_wheel_joint_offset*reflectV} ${wheel_separation/2*reflectH} -${caster_wheel_radius+0.005}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <!-- <xacro:caster prefix="front_left" reflectH="1" reflectV="1"/>
  <xacro:caster prefix="front_right" reflectH="-1" reflectV="1"/> -->
  <xacro:caster prefix="back_left" reflectH="1" reflectV="-1"/>
  <xacro:caster prefix="back_right" reflectH="-1" reflectV="-1"/>

  <xacro:include filename="$(find spot_description)/urdf/spot.plugins.xacro"/>

  <!--<xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
  <VLP-16 parent="base_footprint" name="velodyne" topic="lidar_points" hz="10" samples="1024" gpu="false" lasers="16" max_range="100">
    <origin xyz="0 0 0.73" rpy="0 0 0" />
  </VLP-16>-->

</robot>
