// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: bosdyn/api/license_service.proto

#include "bosdyn/api/license_service.pb.h"
#include "bosdyn/api/license_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace bosdyn {
namespace api {

static const char* LicenseService_method_names[] = {
  "/bosdyn.api.LicenseService/GetLicenseInfo",
};

std::unique_ptr< LicenseService::Stub> LicenseService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LicenseService::Stub> stub(new LicenseService::Stub(channel));
  return stub;
}

LicenseService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetLicenseInfo_(LicenseService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LicenseService::Stub::GetLicenseInfo(::grpc::ClientContext* context, const ::bosdyn::api::GetLicenseInfoRequest& request, ::bosdyn::api::GetLicenseInfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetLicenseInfo_, context, request, response);
}

void LicenseService::Stub::experimental_async::GetLicenseInfo(::grpc::ClientContext* context, const ::bosdyn::api::GetLicenseInfoRequest* request, ::bosdyn::api::GetLicenseInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetLicenseInfo_, context, request, response, std::move(f));
}

void LicenseService::Stub::experimental_async::GetLicenseInfo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::GetLicenseInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetLicenseInfo_, context, request, response, std::move(f));
}

void LicenseService::Stub::experimental_async::GetLicenseInfo(::grpc::ClientContext* context, const ::bosdyn::api::GetLicenseInfoRequest* request, ::bosdyn::api::GetLicenseInfoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetLicenseInfo_, context, request, response, reactor);
}

void LicenseService::Stub::experimental_async::GetLicenseInfo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::GetLicenseInfoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetLicenseInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bosdyn::api::GetLicenseInfoResponse>* LicenseService::Stub::AsyncGetLicenseInfoRaw(::grpc::ClientContext* context, const ::bosdyn::api::GetLicenseInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::bosdyn::api::GetLicenseInfoResponse>::Create(channel_.get(), cq, rpcmethod_GetLicenseInfo_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::bosdyn::api::GetLicenseInfoResponse>* LicenseService::Stub::PrepareAsyncGetLicenseInfoRaw(::grpc::ClientContext* context, const ::bosdyn::api::GetLicenseInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::bosdyn::api::GetLicenseInfoResponse>::Create(channel_.get(), cq, rpcmethod_GetLicenseInfo_, context, request, false);
}

LicenseService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LicenseService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LicenseService::Service, ::bosdyn::api::GetLicenseInfoRequest, ::bosdyn::api::GetLicenseInfoResponse>(
          [](LicenseService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bosdyn::api::GetLicenseInfoRequest* req,
             ::bosdyn::api::GetLicenseInfoResponse* resp) {
               return service->GetLicenseInfo(ctx, req, resp);
             }, this)));
}

LicenseService::Service::~Service() {
}

::grpc::Status LicenseService::Service::GetLicenseInfo(::grpc::ServerContext* context, const ::bosdyn::api::GetLicenseInfoRequest* request, ::bosdyn::api::GetLicenseInfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace bosdyn
}  // namespace api

