// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bosdyn/api/log_annotation.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_bosdyn_2fapi_2flog_5fannotation_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_bosdyn_2fapi_2flog_5fannotation_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "bosdyn/api/header.pb.h"
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_bosdyn_2fapi_2flog_5fannotation_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_bosdyn_2fapi_2flog_5fannotation_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_bosdyn_2fapi_2flog_5fannotation_2eproto;
namespace bosdyn {
namespace api {
class AddLogAnnotationRequest;
class AddLogAnnotationRequestDefaultTypeInternal;
extern AddLogAnnotationRequestDefaultTypeInternal _AddLogAnnotationRequest_default_instance_;
class AddLogAnnotationResponse;
class AddLogAnnotationResponseDefaultTypeInternal;
extern AddLogAnnotationResponseDefaultTypeInternal _AddLogAnnotationResponse_default_instance_;
class LogAnnotationLogBlob;
class LogAnnotationLogBlobDefaultTypeInternal;
extern LogAnnotationLogBlobDefaultTypeInternal _LogAnnotationLogBlob_default_instance_;
class LogAnnotationOperatorMessage;
class LogAnnotationOperatorMessageDefaultTypeInternal;
extern LogAnnotationOperatorMessageDefaultTypeInternal _LogAnnotationOperatorMessage_default_instance_;
class LogAnnotationTextMessage;
class LogAnnotationTextMessageDefaultTypeInternal;
extern LogAnnotationTextMessageDefaultTypeInternal _LogAnnotationTextMessage_default_instance_;
class LogAnnotations;
class LogAnnotationsDefaultTypeInternal;
extern LogAnnotationsDefaultTypeInternal _LogAnnotations_default_instance_;
}  // namespace api
}  // namespace bosdyn
PROTOBUF_NAMESPACE_OPEN
template<> ::bosdyn::api::AddLogAnnotationRequest* Arena::CreateMaybeMessage<::bosdyn::api::AddLogAnnotationRequest>(Arena*);
template<> ::bosdyn::api::AddLogAnnotationResponse* Arena::CreateMaybeMessage<::bosdyn::api::AddLogAnnotationResponse>(Arena*);
template<> ::bosdyn::api::LogAnnotationLogBlob* Arena::CreateMaybeMessage<::bosdyn::api::LogAnnotationLogBlob>(Arena*);
template<> ::bosdyn::api::LogAnnotationOperatorMessage* Arena::CreateMaybeMessage<::bosdyn::api::LogAnnotationOperatorMessage>(Arena*);
template<> ::bosdyn::api::LogAnnotationTextMessage* Arena::CreateMaybeMessage<::bosdyn::api::LogAnnotationTextMessage>(Arena*);
template<> ::bosdyn::api::LogAnnotations* Arena::CreateMaybeMessage<::bosdyn::api::LogAnnotations>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace bosdyn {
namespace api {

enum LogAnnotationTextMessage_Level : int {
  LogAnnotationTextMessage_Level_LEVEL_UNKNOWN = 0,
  LogAnnotationTextMessage_Level_LEVEL_DEBUG = 1,
  LogAnnotationTextMessage_Level_LEVEL_INFO = 2,
  LogAnnotationTextMessage_Level_LEVEL_WARN = 3,
  LogAnnotationTextMessage_Level_LEVEL_ERROR = 4,
  LogAnnotationTextMessage_Level_LogAnnotationTextMessage_Level_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  LogAnnotationTextMessage_Level_LogAnnotationTextMessage_Level_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool LogAnnotationTextMessage_Level_IsValid(int value);
constexpr LogAnnotationTextMessage_Level LogAnnotationTextMessage_Level_Level_MIN = LogAnnotationTextMessage_Level_LEVEL_UNKNOWN;
constexpr LogAnnotationTextMessage_Level LogAnnotationTextMessage_Level_Level_MAX = LogAnnotationTextMessage_Level_LEVEL_ERROR;
constexpr int LogAnnotationTextMessage_Level_Level_ARRAYSIZE = LogAnnotationTextMessage_Level_Level_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LogAnnotationTextMessage_Level_descriptor();
template<typename T>
inline const std::string& LogAnnotationTextMessage_Level_Name(T enum_t_value) {
  static_assert(::std::is_same<T, LogAnnotationTextMessage_Level>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function LogAnnotationTextMessage_Level_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    LogAnnotationTextMessage_Level_descriptor(), enum_t_value);
}
inline bool LogAnnotationTextMessage_Level_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LogAnnotationTextMessage_Level* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LogAnnotationTextMessage_Level>(
    LogAnnotationTextMessage_Level_descriptor(), name, value);
}
// ===================================================================

class AddLogAnnotationRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bosdyn.api.AddLogAnnotationRequest) */ {
 public:
  inline AddLogAnnotationRequest() : AddLogAnnotationRequest(nullptr) {}
  virtual ~AddLogAnnotationRequest();

  AddLogAnnotationRequest(const AddLogAnnotationRequest& from);
  AddLogAnnotationRequest(AddLogAnnotationRequest&& from) noexcept
    : AddLogAnnotationRequest() {
    *this = ::std::move(from);
  }

  inline AddLogAnnotationRequest& operator=(const AddLogAnnotationRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddLogAnnotationRequest& operator=(AddLogAnnotationRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AddLogAnnotationRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AddLogAnnotationRequest* internal_default_instance() {
    return reinterpret_cast<const AddLogAnnotationRequest*>(
               &_AddLogAnnotationRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AddLogAnnotationRequest& a, AddLogAnnotationRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AddLogAnnotationRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddLogAnnotationRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AddLogAnnotationRequest* New() const final {
    return CreateMaybeMessage<AddLogAnnotationRequest>(nullptr);
  }

  AddLogAnnotationRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AddLogAnnotationRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AddLogAnnotationRequest& from);
  void MergeFrom(const AddLogAnnotationRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddLogAnnotationRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bosdyn.api.AddLogAnnotationRequest";
  }
  protected:
  explicit AddLogAnnotationRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_bosdyn_2fapi_2flog_5fannotation_2eproto);
    return ::descriptor_table_bosdyn_2fapi_2flog_5fannotation_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kAnnotationsFieldNumber = 2,
  };
  // .bosdyn.api.RequestHeader header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::bosdyn::api::RequestHeader& header() const;
  ::bosdyn::api::RequestHeader* release_header();
  ::bosdyn::api::RequestHeader* mutable_header();
  void set_allocated_header(::bosdyn::api::RequestHeader* header);
  private:
  const ::bosdyn::api::RequestHeader& _internal_header() const;
  ::bosdyn::api::RequestHeader* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::bosdyn::api::RequestHeader* header);
  ::bosdyn::api::RequestHeader* unsafe_arena_release_header();

  // .bosdyn.api.LogAnnotations annotations = 2;
  bool has_annotations() const;
  private:
  bool _internal_has_annotations() const;
  public:
  void clear_annotations();
  const ::bosdyn::api::LogAnnotations& annotations() const;
  ::bosdyn::api::LogAnnotations* release_annotations();
  ::bosdyn::api::LogAnnotations* mutable_annotations();
  void set_allocated_annotations(::bosdyn::api::LogAnnotations* annotations);
  private:
  const ::bosdyn::api::LogAnnotations& _internal_annotations() const;
  ::bosdyn::api::LogAnnotations* _internal_mutable_annotations();
  public:
  void unsafe_arena_set_allocated_annotations(
      ::bosdyn::api::LogAnnotations* annotations);
  ::bosdyn::api::LogAnnotations* unsafe_arena_release_annotations();

  // @@protoc_insertion_point(class_scope:bosdyn.api.AddLogAnnotationRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::bosdyn::api::RequestHeader* header_;
  ::bosdyn::api::LogAnnotations* annotations_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_bosdyn_2fapi_2flog_5fannotation_2eproto;
};
// -------------------------------------------------------------------

class LogAnnotations PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bosdyn.api.LogAnnotations) */ {
 public:
  inline LogAnnotations() : LogAnnotations(nullptr) {}
  virtual ~LogAnnotations();

  LogAnnotations(const LogAnnotations& from);
  LogAnnotations(LogAnnotations&& from) noexcept
    : LogAnnotations() {
    *this = ::std::move(from);
  }

  inline LogAnnotations& operator=(const LogAnnotations& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogAnnotations& operator=(LogAnnotations&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LogAnnotations& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogAnnotations* internal_default_instance() {
    return reinterpret_cast<const LogAnnotations*>(
               &_LogAnnotations_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(LogAnnotations& a, LogAnnotations& b) {
    a.Swap(&b);
  }
  inline void Swap(LogAnnotations* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogAnnotations* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LogAnnotations* New() const final {
    return CreateMaybeMessage<LogAnnotations>(nullptr);
  }

  LogAnnotations* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LogAnnotations>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LogAnnotations& from);
  void MergeFrom(const LogAnnotations& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogAnnotations* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bosdyn.api.LogAnnotations";
  }
  protected:
  explicit LogAnnotations(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_bosdyn_2fapi_2flog_5fannotation_2eproto);
    return ::descriptor_table_bosdyn_2fapi_2flog_5fannotation_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTextMessagesFieldNumber = 1,
    kOperatorMessagesFieldNumber = 2,
    kBlobDataFieldNumber = 3,
  };
  // repeated .bosdyn.api.LogAnnotationTextMessage text_messages = 1;
  int text_messages_size() const;
  private:
  int _internal_text_messages_size() const;
  public:
  void clear_text_messages();
  ::bosdyn::api::LogAnnotationTextMessage* mutable_text_messages(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bosdyn::api::LogAnnotationTextMessage >*
      mutable_text_messages();
  private:
  const ::bosdyn::api::LogAnnotationTextMessage& _internal_text_messages(int index) const;
  ::bosdyn::api::LogAnnotationTextMessage* _internal_add_text_messages();
  public:
  const ::bosdyn::api::LogAnnotationTextMessage& text_messages(int index) const;
  ::bosdyn::api::LogAnnotationTextMessage* add_text_messages();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bosdyn::api::LogAnnotationTextMessage >&
      text_messages() const;

  // repeated .bosdyn.api.LogAnnotationOperatorMessage operator_messages = 2;
  int operator_messages_size() const;
  private:
  int _internal_operator_messages_size() const;
  public:
  void clear_operator_messages();
  ::bosdyn::api::LogAnnotationOperatorMessage* mutable_operator_messages(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bosdyn::api::LogAnnotationOperatorMessage >*
      mutable_operator_messages();
  private:
  const ::bosdyn::api::LogAnnotationOperatorMessage& _internal_operator_messages(int index) const;
  ::bosdyn::api::LogAnnotationOperatorMessage* _internal_add_operator_messages();
  public:
  const ::bosdyn::api::LogAnnotationOperatorMessage& operator_messages(int index) const;
  ::bosdyn::api::LogAnnotationOperatorMessage* add_operator_messages();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bosdyn::api::LogAnnotationOperatorMessage >&
      operator_messages() const;

  // repeated .bosdyn.api.LogAnnotationLogBlob blob_data = 3;
  int blob_data_size() const;
  private:
  int _internal_blob_data_size() const;
  public:
  void clear_blob_data();
  ::bosdyn::api::LogAnnotationLogBlob* mutable_blob_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bosdyn::api::LogAnnotationLogBlob >*
      mutable_blob_data();
  private:
  const ::bosdyn::api::LogAnnotationLogBlob& _internal_blob_data(int index) const;
  ::bosdyn::api::LogAnnotationLogBlob* _internal_add_blob_data();
  public:
  const ::bosdyn::api::LogAnnotationLogBlob& blob_data(int index) const;
  ::bosdyn::api::LogAnnotationLogBlob* add_blob_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bosdyn::api::LogAnnotationLogBlob >&
      blob_data() const;

  // @@protoc_insertion_point(class_scope:bosdyn.api.LogAnnotations)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bosdyn::api::LogAnnotationTextMessage > text_messages_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bosdyn::api::LogAnnotationOperatorMessage > operator_messages_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bosdyn::api::LogAnnotationLogBlob > blob_data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_bosdyn_2fapi_2flog_5fannotation_2eproto;
};
// -------------------------------------------------------------------

class LogAnnotationTextMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bosdyn.api.LogAnnotationTextMessage) */ {
 public:
  inline LogAnnotationTextMessage() : LogAnnotationTextMessage(nullptr) {}
  virtual ~LogAnnotationTextMessage();

  LogAnnotationTextMessage(const LogAnnotationTextMessage& from);
  LogAnnotationTextMessage(LogAnnotationTextMessage&& from) noexcept
    : LogAnnotationTextMessage() {
    *this = ::std::move(from);
  }

  inline LogAnnotationTextMessage& operator=(const LogAnnotationTextMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogAnnotationTextMessage& operator=(LogAnnotationTextMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LogAnnotationTextMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogAnnotationTextMessage* internal_default_instance() {
    return reinterpret_cast<const LogAnnotationTextMessage*>(
               &_LogAnnotationTextMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(LogAnnotationTextMessage& a, LogAnnotationTextMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(LogAnnotationTextMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogAnnotationTextMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LogAnnotationTextMessage* New() const final {
    return CreateMaybeMessage<LogAnnotationTextMessage>(nullptr);
  }

  LogAnnotationTextMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LogAnnotationTextMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LogAnnotationTextMessage& from);
  void MergeFrom(const LogAnnotationTextMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogAnnotationTextMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bosdyn.api.LogAnnotationTextMessage";
  }
  protected:
  explicit LogAnnotationTextMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_bosdyn_2fapi_2flog_5fannotation_2eproto);
    return ::descriptor_table_bosdyn_2fapi_2flog_5fannotation_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef LogAnnotationTextMessage_Level Level;
  static constexpr Level LEVEL_UNKNOWN =
    LogAnnotationTextMessage_Level_LEVEL_UNKNOWN;
  static constexpr Level LEVEL_DEBUG =
    LogAnnotationTextMessage_Level_LEVEL_DEBUG;
  static constexpr Level LEVEL_INFO =
    LogAnnotationTextMessage_Level_LEVEL_INFO;
  static constexpr Level LEVEL_WARN =
    LogAnnotationTextMessage_Level_LEVEL_WARN;
  static constexpr Level LEVEL_ERROR =
    LogAnnotationTextMessage_Level_LEVEL_ERROR;
  static inline bool Level_IsValid(int value) {
    return LogAnnotationTextMessage_Level_IsValid(value);
  }
  static constexpr Level Level_MIN =
    LogAnnotationTextMessage_Level_Level_MIN;
  static constexpr Level Level_MAX =
    LogAnnotationTextMessage_Level_Level_MAX;
  static constexpr int Level_ARRAYSIZE =
    LogAnnotationTextMessage_Level_Level_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Level_descriptor() {
    return LogAnnotationTextMessage_Level_descriptor();
  }
  template<typename T>
  static inline const std::string& Level_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Level>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Level_Name.");
    return LogAnnotationTextMessage_Level_Name(enum_t_value);
  }
  static inline bool Level_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Level* value) {
    return LogAnnotationTextMessage_Level_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
    kServiceFieldNumber = 3,
    kTagFieldNumber = 5,
    kFilenameFieldNumber = 6,
    kTimestampFieldNumber = 2,
    kLevelFieldNumber = 4,
    kLineNumberFieldNumber = 7,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // string service = 3;
  void clear_service();
  const std::string& service() const;
  void set_service(const std::string& value);
  void set_service(std::string&& value);
  void set_service(const char* value);
  void set_service(const char* value, size_t size);
  std::string* mutable_service();
  std::string* release_service();
  void set_allocated_service(std::string* service);
  private:
  const std::string& _internal_service() const;
  void _internal_set_service(const std::string& value);
  std::string* _internal_mutable_service();
  public:

  // string tag = 5;
  void clear_tag();
  const std::string& tag() const;
  void set_tag(const std::string& value);
  void set_tag(std::string&& value);
  void set_tag(const char* value);
  void set_tag(const char* value, size_t size);
  std::string* mutable_tag();
  std::string* release_tag();
  void set_allocated_tag(std::string* tag);
  private:
  const std::string& _internal_tag() const;
  void _internal_set_tag(const std::string& value);
  std::string* _internal_mutable_tag();
  public:

  // string filename = 6;
  void clear_filename();
  const std::string& filename() const;
  void set_filename(const std::string& value);
  void set_filename(std::string&& value);
  void set_filename(const char* value);
  void set_filename(const char* value, size_t size);
  std::string* mutable_filename();
  std::string* release_filename();
  void set_allocated_filename(std::string* filename);
  private:
  const std::string& _internal_filename() const;
  void _internal_set_filename(const std::string& value);
  std::string* _internal_mutable_filename();
  public:

  // .google.protobuf.Timestamp timestamp = 2;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // .bosdyn.api.LogAnnotationTextMessage.Level level = 4;
  void clear_level();
  ::bosdyn::api::LogAnnotationTextMessage_Level level() const;
  void set_level(::bosdyn::api::LogAnnotationTextMessage_Level value);
  private:
  ::bosdyn::api::LogAnnotationTextMessage_Level _internal_level() const;
  void _internal_set_level(::bosdyn::api::LogAnnotationTextMessage_Level value);
  public:

  // int32 line_number = 7;
  void clear_line_number();
  ::PROTOBUF_NAMESPACE_ID::int32 line_number() const;
  void set_line_number(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_line_number() const;
  void _internal_set_line_number(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:bosdyn.api.LogAnnotationTextMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tag_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filename_;
  PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  int level_;
  ::PROTOBUF_NAMESPACE_ID::int32 line_number_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_bosdyn_2fapi_2flog_5fannotation_2eproto;
};
// -------------------------------------------------------------------

class LogAnnotationOperatorMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bosdyn.api.LogAnnotationOperatorMessage) */ {
 public:
  inline LogAnnotationOperatorMessage() : LogAnnotationOperatorMessage(nullptr) {}
  virtual ~LogAnnotationOperatorMessage();

  LogAnnotationOperatorMessage(const LogAnnotationOperatorMessage& from);
  LogAnnotationOperatorMessage(LogAnnotationOperatorMessage&& from) noexcept
    : LogAnnotationOperatorMessage() {
    *this = ::std::move(from);
  }

  inline LogAnnotationOperatorMessage& operator=(const LogAnnotationOperatorMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogAnnotationOperatorMessage& operator=(LogAnnotationOperatorMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LogAnnotationOperatorMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogAnnotationOperatorMessage* internal_default_instance() {
    return reinterpret_cast<const LogAnnotationOperatorMessage*>(
               &_LogAnnotationOperatorMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(LogAnnotationOperatorMessage& a, LogAnnotationOperatorMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(LogAnnotationOperatorMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogAnnotationOperatorMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LogAnnotationOperatorMessage* New() const final {
    return CreateMaybeMessage<LogAnnotationOperatorMessage>(nullptr);
  }

  LogAnnotationOperatorMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LogAnnotationOperatorMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LogAnnotationOperatorMessage& from);
  void MergeFrom(const LogAnnotationOperatorMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogAnnotationOperatorMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bosdyn.api.LogAnnotationOperatorMessage";
  }
  protected:
  explicit LogAnnotationOperatorMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_bosdyn_2fapi_2flog_5fannotation_2eproto);
    return ::descriptor_table_bosdyn_2fapi_2flog_5fannotation_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
    kTimestampFieldNumber = 2,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // .google.protobuf.Timestamp timestamp = 2;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // @@protoc_insertion_point(class_scope:bosdyn.api.LogAnnotationOperatorMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_bosdyn_2fapi_2flog_5fannotation_2eproto;
};
// -------------------------------------------------------------------

class LogAnnotationLogBlob PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bosdyn.api.LogAnnotationLogBlob) */ {
 public:
  inline LogAnnotationLogBlob() : LogAnnotationLogBlob(nullptr) {}
  virtual ~LogAnnotationLogBlob();

  LogAnnotationLogBlob(const LogAnnotationLogBlob& from);
  LogAnnotationLogBlob(LogAnnotationLogBlob&& from) noexcept
    : LogAnnotationLogBlob() {
    *this = ::std::move(from);
  }

  inline LogAnnotationLogBlob& operator=(const LogAnnotationLogBlob& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogAnnotationLogBlob& operator=(LogAnnotationLogBlob&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LogAnnotationLogBlob& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogAnnotationLogBlob* internal_default_instance() {
    return reinterpret_cast<const LogAnnotationLogBlob*>(
               &_LogAnnotationLogBlob_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(LogAnnotationLogBlob& a, LogAnnotationLogBlob& b) {
    a.Swap(&b);
  }
  inline void Swap(LogAnnotationLogBlob* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogAnnotationLogBlob* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LogAnnotationLogBlob* New() const final {
    return CreateMaybeMessage<LogAnnotationLogBlob>(nullptr);
  }

  LogAnnotationLogBlob* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LogAnnotationLogBlob>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LogAnnotationLogBlob& from);
  void MergeFrom(const LogAnnotationLogBlob& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogAnnotationLogBlob* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bosdyn.api.LogAnnotationLogBlob";
  }
  protected:
  explicit LogAnnotationLogBlob(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_bosdyn_2fapi_2flog_5fannotation_2eproto);
    return ::descriptor_table_bosdyn_2fapi_2flog_5fannotation_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChannelFieldNumber = 2,
    kTypeIdFieldNumber = 3,
    kDataFieldNumber = 4,
    kTimestampFieldNumber = 1,
  };
  // string channel = 2;
  void clear_channel();
  const std::string& channel() const;
  void set_channel(const std::string& value);
  void set_channel(std::string&& value);
  void set_channel(const char* value);
  void set_channel(const char* value, size_t size);
  std::string* mutable_channel();
  std::string* release_channel();
  void set_allocated_channel(std::string* channel);
  private:
  const std::string& _internal_channel() const;
  void _internal_set_channel(const std::string& value);
  std::string* _internal_mutable_channel();
  public:

  // string type_id = 3;
  void clear_type_id();
  const std::string& type_id() const;
  void set_type_id(const std::string& value);
  void set_type_id(std::string&& value);
  void set_type_id(const char* value);
  void set_type_id(const char* value, size_t size);
  std::string* mutable_type_id();
  std::string* release_type_id();
  void set_allocated_type_id(std::string* type_id);
  private:
  const std::string& _internal_type_id() const;
  void _internal_set_type_id(const std::string& value);
  std::string* _internal_mutable_type_id();
  public:

  // bytes data = 4;
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // .google.protobuf.Timestamp timestamp = 1;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // @@protoc_insertion_point(class_scope:bosdyn.api.LogAnnotationLogBlob)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr channel_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_bosdyn_2fapi_2flog_5fannotation_2eproto;
};
// -------------------------------------------------------------------

class AddLogAnnotationResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bosdyn.api.AddLogAnnotationResponse) */ {
 public:
  inline AddLogAnnotationResponse() : AddLogAnnotationResponse(nullptr) {}
  virtual ~AddLogAnnotationResponse();

  AddLogAnnotationResponse(const AddLogAnnotationResponse& from);
  AddLogAnnotationResponse(AddLogAnnotationResponse&& from) noexcept
    : AddLogAnnotationResponse() {
    *this = ::std::move(from);
  }

  inline AddLogAnnotationResponse& operator=(const AddLogAnnotationResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddLogAnnotationResponse& operator=(AddLogAnnotationResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AddLogAnnotationResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AddLogAnnotationResponse* internal_default_instance() {
    return reinterpret_cast<const AddLogAnnotationResponse*>(
               &_AddLogAnnotationResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(AddLogAnnotationResponse& a, AddLogAnnotationResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(AddLogAnnotationResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddLogAnnotationResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AddLogAnnotationResponse* New() const final {
    return CreateMaybeMessage<AddLogAnnotationResponse>(nullptr);
  }

  AddLogAnnotationResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AddLogAnnotationResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AddLogAnnotationResponse& from);
  void MergeFrom(const AddLogAnnotationResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddLogAnnotationResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bosdyn.api.AddLogAnnotationResponse";
  }
  protected:
  explicit AddLogAnnotationResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_bosdyn_2fapi_2flog_5fannotation_2eproto);
    return ::descriptor_table_bosdyn_2fapi_2flog_5fannotation_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
  };
  // .bosdyn.api.ResponseHeader header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::bosdyn::api::ResponseHeader& header() const;
  ::bosdyn::api::ResponseHeader* release_header();
  ::bosdyn::api::ResponseHeader* mutable_header();
  void set_allocated_header(::bosdyn::api::ResponseHeader* header);
  private:
  const ::bosdyn::api::ResponseHeader& _internal_header() const;
  ::bosdyn::api::ResponseHeader* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::bosdyn::api::ResponseHeader* header);
  ::bosdyn::api::ResponseHeader* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:bosdyn.api.AddLogAnnotationResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::bosdyn::api::ResponseHeader* header_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_bosdyn_2fapi_2flog_5fannotation_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AddLogAnnotationRequest

// .bosdyn.api.RequestHeader header = 1;
inline bool AddLogAnnotationRequest::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool AddLogAnnotationRequest::has_header() const {
  return _internal_has_header();
}
inline const ::bosdyn::api::RequestHeader& AddLogAnnotationRequest::_internal_header() const {
  const ::bosdyn::api::RequestHeader* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::bosdyn::api::RequestHeader*>(
      &::bosdyn::api::_RequestHeader_default_instance_);
}
inline const ::bosdyn::api::RequestHeader& AddLogAnnotationRequest::header() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.AddLogAnnotationRequest.header)
  return _internal_header();
}
inline void AddLogAnnotationRequest::unsafe_arena_set_allocated_header(
    ::bosdyn::api::RequestHeader* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:bosdyn.api.AddLogAnnotationRequest.header)
}
inline ::bosdyn::api::RequestHeader* AddLogAnnotationRequest::release_header() {
  
  ::bosdyn::api::RequestHeader* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::bosdyn::api::RequestHeader* AddLogAnnotationRequest::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:bosdyn.api.AddLogAnnotationRequest.header)
  
  ::bosdyn::api::RequestHeader* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::bosdyn::api::RequestHeader* AddLogAnnotationRequest::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::bosdyn::api::RequestHeader>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::bosdyn::api::RequestHeader* AddLogAnnotationRequest::mutable_header() {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.AddLogAnnotationRequest.header)
  return _internal_mutable_header();
}
inline void AddLogAnnotationRequest::set_allocated_header(::bosdyn::api::RequestHeader* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.AddLogAnnotationRequest.header)
}

// .bosdyn.api.LogAnnotations annotations = 2;
inline bool AddLogAnnotationRequest::_internal_has_annotations() const {
  return this != internal_default_instance() && annotations_ != nullptr;
}
inline bool AddLogAnnotationRequest::has_annotations() const {
  return _internal_has_annotations();
}
inline void AddLogAnnotationRequest::clear_annotations() {
  if (GetArena() == nullptr && annotations_ != nullptr) {
    delete annotations_;
  }
  annotations_ = nullptr;
}
inline const ::bosdyn::api::LogAnnotations& AddLogAnnotationRequest::_internal_annotations() const {
  const ::bosdyn::api::LogAnnotations* p = annotations_;
  return p != nullptr ? *p : *reinterpret_cast<const ::bosdyn::api::LogAnnotations*>(
      &::bosdyn::api::_LogAnnotations_default_instance_);
}
inline const ::bosdyn::api::LogAnnotations& AddLogAnnotationRequest::annotations() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.AddLogAnnotationRequest.annotations)
  return _internal_annotations();
}
inline void AddLogAnnotationRequest::unsafe_arena_set_allocated_annotations(
    ::bosdyn::api::LogAnnotations* annotations) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(annotations_);
  }
  annotations_ = annotations;
  if (annotations) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:bosdyn.api.AddLogAnnotationRequest.annotations)
}
inline ::bosdyn::api::LogAnnotations* AddLogAnnotationRequest::release_annotations() {
  
  ::bosdyn::api::LogAnnotations* temp = annotations_;
  annotations_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::bosdyn::api::LogAnnotations* AddLogAnnotationRequest::unsafe_arena_release_annotations() {
  // @@protoc_insertion_point(field_release:bosdyn.api.AddLogAnnotationRequest.annotations)
  
  ::bosdyn::api::LogAnnotations* temp = annotations_;
  annotations_ = nullptr;
  return temp;
}
inline ::bosdyn::api::LogAnnotations* AddLogAnnotationRequest::_internal_mutable_annotations() {
  
  if (annotations_ == nullptr) {
    auto* p = CreateMaybeMessage<::bosdyn::api::LogAnnotations>(GetArena());
    annotations_ = p;
  }
  return annotations_;
}
inline ::bosdyn::api::LogAnnotations* AddLogAnnotationRequest::mutable_annotations() {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.AddLogAnnotationRequest.annotations)
  return _internal_mutable_annotations();
}
inline void AddLogAnnotationRequest::set_allocated_annotations(::bosdyn::api::LogAnnotations* annotations) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete annotations_;
  }
  if (annotations) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(annotations);
    if (message_arena != submessage_arena) {
      annotations = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, annotations, submessage_arena);
    }
    
  } else {
    
  }
  annotations_ = annotations;
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.AddLogAnnotationRequest.annotations)
}

// -------------------------------------------------------------------

// LogAnnotations

// repeated .bosdyn.api.LogAnnotationTextMessage text_messages = 1;
inline int LogAnnotations::_internal_text_messages_size() const {
  return text_messages_.size();
}
inline int LogAnnotations::text_messages_size() const {
  return _internal_text_messages_size();
}
inline void LogAnnotations::clear_text_messages() {
  text_messages_.Clear();
}
inline ::bosdyn::api::LogAnnotationTextMessage* LogAnnotations::mutable_text_messages(int index) {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.LogAnnotations.text_messages)
  return text_messages_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bosdyn::api::LogAnnotationTextMessage >*
LogAnnotations::mutable_text_messages() {
  // @@protoc_insertion_point(field_mutable_list:bosdyn.api.LogAnnotations.text_messages)
  return &text_messages_;
}
inline const ::bosdyn::api::LogAnnotationTextMessage& LogAnnotations::_internal_text_messages(int index) const {
  return text_messages_.Get(index);
}
inline const ::bosdyn::api::LogAnnotationTextMessage& LogAnnotations::text_messages(int index) const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotations.text_messages)
  return _internal_text_messages(index);
}
inline ::bosdyn::api::LogAnnotationTextMessage* LogAnnotations::_internal_add_text_messages() {
  return text_messages_.Add();
}
inline ::bosdyn::api::LogAnnotationTextMessage* LogAnnotations::add_text_messages() {
  // @@protoc_insertion_point(field_add:bosdyn.api.LogAnnotations.text_messages)
  return _internal_add_text_messages();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bosdyn::api::LogAnnotationTextMessage >&
LogAnnotations::text_messages() const {
  // @@protoc_insertion_point(field_list:bosdyn.api.LogAnnotations.text_messages)
  return text_messages_;
}

// repeated .bosdyn.api.LogAnnotationOperatorMessage operator_messages = 2;
inline int LogAnnotations::_internal_operator_messages_size() const {
  return operator_messages_.size();
}
inline int LogAnnotations::operator_messages_size() const {
  return _internal_operator_messages_size();
}
inline void LogAnnotations::clear_operator_messages() {
  operator_messages_.Clear();
}
inline ::bosdyn::api::LogAnnotationOperatorMessage* LogAnnotations::mutable_operator_messages(int index) {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.LogAnnotations.operator_messages)
  return operator_messages_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bosdyn::api::LogAnnotationOperatorMessage >*
LogAnnotations::mutable_operator_messages() {
  // @@protoc_insertion_point(field_mutable_list:bosdyn.api.LogAnnotations.operator_messages)
  return &operator_messages_;
}
inline const ::bosdyn::api::LogAnnotationOperatorMessage& LogAnnotations::_internal_operator_messages(int index) const {
  return operator_messages_.Get(index);
}
inline const ::bosdyn::api::LogAnnotationOperatorMessage& LogAnnotations::operator_messages(int index) const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotations.operator_messages)
  return _internal_operator_messages(index);
}
inline ::bosdyn::api::LogAnnotationOperatorMessage* LogAnnotations::_internal_add_operator_messages() {
  return operator_messages_.Add();
}
inline ::bosdyn::api::LogAnnotationOperatorMessage* LogAnnotations::add_operator_messages() {
  // @@protoc_insertion_point(field_add:bosdyn.api.LogAnnotations.operator_messages)
  return _internal_add_operator_messages();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bosdyn::api::LogAnnotationOperatorMessage >&
LogAnnotations::operator_messages() const {
  // @@protoc_insertion_point(field_list:bosdyn.api.LogAnnotations.operator_messages)
  return operator_messages_;
}

// repeated .bosdyn.api.LogAnnotationLogBlob blob_data = 3;
inline int LogAnnotations::_internal_blob_data_size() const {
  return blob_data_.size();
}
inline int LogAnnotations::blob_data_size() const {
  return _internal_blob_data_size();
}
inline void LogAnnotations::clear_blob_data() {
  blob_data_.Clear();
}
inline ::bosdyn::api::LogAnnotationLogBlob* LogAnnotations::mutable_blob_data(int index) {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.LogAnnotations.blob_data)
  return blob_data_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bosdyn::api::LogAnnotationLogBlob >*
LogAnnotations::mutable_blob_data() {
  // @@protoc_insertion_point(field_mutable_list:bosdyn.api.LogAnnotations.blob_data)
  return &blob_data_;
}
inline const ::bosdyn::api::LogAnnotationLogBlob& LogAnnotations::_internal_blob_data(int index) const {
  return blob_data_.Get(index);
}
inline const ::bosdyn::api::LogAnnotationLogBlob& LogAnnotations::blob_data(int index) const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotations.blob_data)
  return _internal_blob_data(index);
}
inline ::bosdyn::api::LogAnnotationLogBlob* LogAnnotations::_internal_add_blob_data() {
  return blob_data_.Add();
}
inline ::bosdyn::api::LogAnnotationLogBlob* LogAnnotations::add_blob_data() {
  // @@protoc_insertion_point(field_add:bosdyn.api.LogAnnotations.blob_data)
  return _internal_add_blob_data();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bosdyn::api::LogAnnotationLogBlob >&
LogAnnotations::blob_data() const {
  // @@protoc_insertion_point(field_list:bosdyn.api.LogAnnotations.blob_data)
  return blob_data_;
}

// -------------------------------------------------------------------

// LogAnnotationTextMessage

// string message = 1;
inline void LogAnnotationTextMessage::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& LogAnnotationTextMessage::message() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotationTextMessage.message)
  return _internal_message();
}
inline void LogAnnotationTextMessage::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:bosdyn.api.LogAnnotationTextMessage.message)
}
inline std::string* LogAnnotationTextMessage::mutable_message() {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.LogAnnotationTextMessage.message)
  return _internal_mutable_message();
}
inline const std::string& LogAnnotationTextMessage::_internal_message() const {
  return message_.Get();
}
inline void LogAnnotationTextMessage::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LogAnnotationTextMessage::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bosdyn.api.LogAnnotationTextMessage.message)
}
inline void LogAnnotationTextMessage::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:bosdyn.api.LogAnnotationTextMessage.message)
}
inline void LogAnnotationTextMessage::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bosdyn.api.LogAnnotationTextMessage.message)
}
inline std::string* LogAnnotationTextMessage::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LogAnnotationTextMessage::release_message() {
  // @@protoc_insertion_point(field_release:bosdyn.api.LogAnnotationTextMessage.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogAnnotationTextMessage::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.LogAnnotationTextMessage.message)
}

// .google.protobuf.Timestamp timestamp = 2;
inline bool LogAnnotationTextMessage::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool LogAnnotationTextMessage::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& LogAnnotationTextMessage::_internal_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& LogAnnotationTextMessage::timestamp() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotationTextMessage.timestamp)
  return _internal_timestamp();
}
inline void LogAnnotationTextMessage::unsafe_arena_set_allocated_timestamp(
    PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:bosdyn.api.LogAnnotationTextMessage.timestamp)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* LogAnnotationTextMessage::release_timestamp() {
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* LogAnnotationTextMessage::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:bosdyn.api.LogAnnotationTextMessage.timestamp)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* LogAnnotationTextMessage::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    timestamp_ = p;
  }
  return timestamp_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* LogAnnotationTextMessage::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.LogAnnotationTextMessage.timestamp)
  return _internal_mutable_timestamp();
}
inline void LogAnnotationTextMessage::set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.LogAnnotationTextMessage.timestamp)
}

// string service = 3;
inline void LogAnnotationTextMessage::clear_service() {
  service_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& LogAnnotationTextMessage::service() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotationTextMessage.service)
  return _internal_service();
}
inline void LogAnnotationTextMessage::set_service(const std::string& value) {
  _internal_set_service(value);
  // @@protoc_insertion_point(field_set:bosdyn.api.LogAnnotationTextMessage.service)
}
inline std::string* LogAnnotationTextMessage::mutable_service() {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.LogAnnotationTextMessage.service)
  return _internal_mutable_service();
}
inline const std::string& LogAnnotationTextMessage::_internal_service() const {
  return service_.Get();
}
inline void LogAnnotationTextMessage::_internal_set_service(const std::string& value) {
  
  service_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LogAnnotationTextMessage::set_service(std::string&& value) {
  
  service_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bosdyn.api.LogAnnotationTextMessage.service)
}
inline void LogAnnotationTextMessage::set_service(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  service_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:bosdyn.api.LogAnnotationTextMessage.service)
}
inline void LogAnnotationTextMessage::set_service(const char* value,
    size_t size) {
  
  service_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bosdyn.api.LogAnnotationTextMessage.service)
}
inline std::string* LogAnnotationTextMessage::_internal_mutable_service() {
  
  return service_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LogAnnotationTextMessage::release_service() {
  // @@protoc_insertion_point(field_release:bosdyn.api.LogAnnotationTextMessage.service)
  return service_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogAnnotationTextMessage::set_allocated_service(std::string* service) {
  if (service != nullptr) {
    
  } else {
    
  }
  service_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), service,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.LogAnnotationTextMessage.service)
}

// .bosdyn.api.LogAnnotationTextMessage.Level level = 4;
inline void LogAnnotationTextMessage::clear_level() {
  level_ = 0;
}
inline ::bosdyn::api::LogAnnotationTextMessage_Level LogAnnotationTextMessage::_internal_level() const {
  return static_cast< ::bosdyn::api::LogAnnotationTextMessage_Level >(level_);
}
inline ::bosdyn::api::LogAnnotationTextMessage_Level LogAnnotationTextMessage::level() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotationTextMessage.level)
  return _internal_level();
}
inline void LogAnnotationTextMessage::_internal_set_level(::bosdyn::api::LogAnnotationTextMessage_Level value) {
  
  level_ = value;
}
inline void LogAnnotationTextMessage::set_level(::bosdyn::api::LogAnnotationTextMessage_Level value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:bosdyn.api.LogAnnotationTextMessage.level)
}

// string tag = 5;
inline void LogAnnotationTextMessage::clear_tag() {
  tag_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& LogAnnotationTextMessage::tag() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotationTextMessage.tag)
  return _internal_tag();
}
inline void LogAnnotationTextMessage::set_tag(const std::string& value) {
  _internal_set_tag(value);
  // @@protoc_insertion_point(field_set:bosdyn.api.LogAnnotationTextMessage.tag)
}
inline std::string* LogAnnotationTextMessage::mutable_tag() {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.LogAnnotationTextMessage.tag)
  return _internal_mutable_tag();
}
inline const std::string& LogAnnotationTextMessage::_internal_tag() const {
  return tag_.Get();
}
inline void LogAnnotationTextMessage::_internal_set_tag(const std::string& value) {
  
  tag_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LogAnnotationTextMessage::set_tag(std::string&& value) {
  
  tag_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bosdyn.api.LogAnnotationTextMessage.tag)
}
inline void LogAnnotationTextMessage::set_tag(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  tag_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:bosdyn.api.LogAnnotationTextMessage.tag)
}
inline void LogAnnotationTextMessage::set_tag(const char* value,
    size_t size) {
  
  tag_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bosdyn.api.LogAnnotationTextMessage.tag)
}
inline std::string* LogAnnotationTextMessage::_internal_mutable_tag() {
  
  return tag_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LogAnnotationTextMessage::release_tag() {
  // @@protoc_insertion_point(field_release:bosdyn.api.LogAnnotationTextMessage.tag)
  return tag_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogAnnotationTextMessage::set_allocated_tag(std::string* tag) {
  if (tag != nullptr) {
    
  } else {
    
  }
  tag_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), tag,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.LogAnnotationTextMessage.tag)
}

// string filename = 6;
inline void LogAnnotationTextMessage::clear_filename() {
  filename_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& LogAnnotationTextMessage::filename() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotationTextMessage.filename)
  return _internal_filename();
}
inline void LogAnnotationTextMessage::set_filename(const std::string& value) {
  _internal_set_filename(value);
  // @@protoc_insertion_point(field_set:bosdyn.api.LogAnnotationTextMessage.filename)
}
inline std::string* LogAnnotationTextMessage::mutable_filename() {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.LogAnnotationTextMessage.filename)
  return _internal_mutable_filename();
}
inline const std::string& LogAnnotationTextMessage::_internal_filename() const {
  return filename_.Get();
}
inline void LogAnnotationTextMessage::_internal_set_filename(const std::string& value) {
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LogAnnotationTextMessage::set_filename(std::string&& value) {
  
  filename_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bosdyn.api.LogAnnotationTextMessage.filename)
}
inline void LogAnnotationTextMessage::set_filename(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:bosdyn.api.LogAnnotationTextMessage.filename)
}
inline void LogAnnotationTextMessage::set_filename(const char* value,
    size_t size) {
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bosdyn.api.LogAnnotationTextMessage.filename)
}
inline std::string* LogAnnotationTextMessage::_internal_mutable_filename() {
  
  return filename_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LogAnnotationTextMessage::release_filename() {
  // @@protoc_insertion_point(field_release:bosdyn.api.LogAnnotationTextMessage.filename)
  return filename_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogAnnotationTextMessage::set_allocated_filename(std::string* filename) {
  if (filename != nullptr) {
    
  } else {
    
  }
  filename_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), filename,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.LogAnnotationTextMessage.filename)
}

// int32 line_number = 7;
inline void LogAnnotationTextMessage::clear_line_number() {
  line_number_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LogAnnotationTextMessage::_internal_line_number() const {
  return line_number_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LogAnnotationTextMessage::line_number() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotationTextMessage.line_number)
  return _internal_line_number();
}
inline void LogAnnotationTextMessage::_internal_set_line_number(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  line_number_ = value;
}
inline void LogAnnotationTextMessage::set_line_number(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_line_number(value);
  // @@protoc_insertion_point(field_set:bosdyn.api.LogAnnotationTextMessage.line_number)
}

// -------------------------------------------------------------------

// LogAnnotationOperatorMessage

// string message = 1;
inline void LogAnnotationOperatorMessage::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& LogAnnotationOperatorMessage::message() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotationOperatorMessage.message)
  return _internal_message();
}
inline void LogAnnotationOperatorMessage::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:bosdyn.api.LogAnnotationOperatorMessage.message)
}
inline std::string* LogAnnotationOperatorMessage::mutable_message() {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.LogAnnotationOperatorMessage.message)
  return _internal_mutable_message();
}
inline const std::string& LogAnnotationOperatorMessage::_internal_message() const {
  return message_.Get();
}
inline void LogAnnotationOperatorMessage::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LogAnnotationOperatorMessage::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bosdyn.api.LogAnnotationOperatorMessage.message)
}
inline void LogAnnotationOperatorMessage::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:bosdyn.api.LogAnnotationOperatorMessage.message)
}
inline void LogAnnotationOperatorMessage::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bosdyn.api.LogAnnotationOperatorMessage.message)
}
inline std::string* LogAnnotationOperatorMessage::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LogAnnotationOperatorMessage::release_message() {
  // @@protoc_insertion_point(field_release:bosdyn.api.LogAnnotationOperatorMessage.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogAnnotationOperatorMessage::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.LogAnnotationOperatorMessage.message)
}

// .google.protobuf.Timestamp timestamp = 2;
inline bool LogAnnotationOperatorMessage::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool LogAnnotationOperatorMessage::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& LogAnnotationOperatorMessage::_internal_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& LogAnnotationOperatorMessage::timestamp() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotationOperatorMessage.timestamp)
  return _internal_timestamp();
}
inline void LogAnnotationOperatorMessage::unsafe_arena_set_allocated_timestamp(
    PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:bosdyn.api.LogAnnotationOperatorMessage.timestamp)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* LogAnnotationOperatorMessage::release_timestamp() {
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* LogAnnotationOperatorMessage::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:bosdyn.api.LogAnnotationOperatorMessage.timestamp)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* LogAnnotationOperatorMessage::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    timestamp_ = p;
  }
  return timestamp_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* LogAnnotationOperatorMessage::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.LogAnnotationOperatorMessage.timestamp)
  return _internal_mutable_timestamp();
}
inline void LogAnnotationOperatorMessage::set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.LogAnnotationOperatorMessage.timestamp)
}

// -------------------------------------------------------------------

// LogAnnotationLogBlob

// .google.protobuf.Timestamp timestamp = 1;
inline bool LogAnnotationLogBlob::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool LogAnnotationLogBlob::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& LogAnnotationLogBlob::_internal_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& LogAnnotationLogBlob::timestamp() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotationLogBlob.timestamp)
  return _internal_timestamp();
}
inline void LogAnnotationLogBlob::unsafe_arena_set_allocated_timestamp(
    PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:bosdyn.api.LogAnnotationLogBlob.timestamp)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* LogAnnotationLogBlob::release_timestamp() {
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* LogAnnotationLogBlob::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:bosdyn.api.LogAnnotationLogBlob.timestamp)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* LogAnnotationLogBlob::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArena());
    timestamp_ = p;
  }
  return timestamp_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* LogAnnotationLogBlob::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.LogAnnotationLogBlob.timestamp)
  return _internal_mutable_timestamp();
}
inline void LogAnnotationLogBlob::set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.LogAnnotationLogBlob.timestamp)
}

// string channel = 2;
inline void LogAnnotationLogBlob::clear_channel() {
  channel_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& LogAnnotationLogBlob::channel() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotationLogBlob.channel)
  return _internal_channel();
}
inline void LogAnnotationLogBlob::set_channel(const std::string& value) {
  _internal_set_channel(value);
  // @@protoc_insertion_point(field_set:bosdyn.api.LogAnnotationLogBlob.channel)
}
inline std::string* LogAnnotationLogBlob::mutable_channel() {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.LogAnnotationLogBlob.channel)
  return _internal_mutable_channel();
}
inline const std::string& LogAnnotationLogBlob::_internal_channel() const {
  return channel_.Get();
}
inline void LogAnnotationLogBlob::_internal_set_channel(const std::string& value) {
  
  channel_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LogAnnotationLogBlob::set_channel(std::string&& value) {
  
  channel_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bosdyn.api.LogAnnotationLogBlob.channel)
}
inline void LogAnnotationLogBlob::set_channel(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  channel_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:bosdyn.api.LogAnnotationLogBlob.channel)
}
inline void LogAnnotationLogBlob::set_channel(const char* value,
    size_t size) {
  
  channel_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bosdyn.api.LogAnnotationLogBlob.channel)
}
inline std::string* LogAnnotationLogBlob::_internal_mutable_channel() {
  
  return channel_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LogAnnotationLogBlob::release_channel() {
  // @@protoc_insertion_point(field_release:bosdyn.api.LogAnnotationLogBlob.channel)
  return channel_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogAnnotationLogBlob::set_allocated_channel(std::string* channel) {
  if (channel != nullptr) {
    
  } else {
    
  }
  channel_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), channel,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.LogAnnotationLogBlob.channel)
}

// string type_id = 3;
inline void LogAnnotationLogBlob::clear_type_id() {
  type_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& LogAnnotationLogBlob::type_id() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotationLogBlob.type_id)
  return _internal_type_id();
}
inline void LogAnnotationLogBlob::set_type_id(const std::string& value) {
  _internal_set_type_id(value);
  // @@protoc_insertion_point(field_set:bosdyn.api.LogAnnotationLogBlob.type_id)
}
inline std::string* LogAnnotationLogBlob::mutable_type_id() {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.LogAnnotationLogBlob.type_id)
  return _internal_mutable_type_id();
}
inline const std::string& LogAnnotationLogBlob::_internal_type_id() const {
  return type_id_.Get();
}
inline void LogAnnotationLogBlob::_internal_set_type_id(const std::string& value) {
  
  type_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LogAnnotationLogBlob::set_type_id(std::string&& value) {
  
  type_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bosdyn.api.LogAnnotationLogBlob.type_id)
}
inline void LogAnnotationLogBlob::set_type_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  type_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:bosdyn.api.LogAnnotationLogBlob.type_id)
}
inline void LogAnnotationLogBlob::set_type_id(const char* value,
    size_t size) {
  
  type_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bosdyn.api.LogAnnotationLogBlob.type_id)
}
inline std::string* LogAnnotationLogBlob::_internal_mutable_type_id() {
  
  return type_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LogAnnotationLogBlob::release_type_id() {
  // @@protoc_insertion_point(field_release:bosdyn.api.LogAnnotationLogBlob.type_id)
  return type_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogAnnotationLogBlob::set_allocated_type_id(std::string* type_id) {
  if (type_id != nullptr) {
    
  } else {
    
  }
  type_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), type_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.LogAnnotationLogBlob.type_id)
}

// bytes data = 4;
inline void LogAnnotationLogBlob::clear_data() {
  data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& LogAnnotationLogBlob::data() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.LogAnnotationLogBlob.data)
  return _internal_data();
}
inline void LogAnnotationLogBlob::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:bosdyn.api.LogAnnotationLogBlob.data)
}
inline std::string* LogAnnotationLogBlob::mutable_data() {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.LogAnnotationLogBlob.data)
  return _internal_mutable_data();
}
inline const std::string& LogAnnotationLogBlob::_internal_data() const {
  return data_.Get();
}
inline void LogAnnotationLogBlob::_internal_set_data(const std::string& value) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LogAnnotationLogBlob::set_data(std::string&& value) {
  
  data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:bosdyn.api.LogAnnotationLogBlob.data)
}
inline void LogAnnotationLogBlob::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:bosdyn.api.LogAnnotationLogBlob.data)
}
inline void LogAnnotationLogBlob::set_data(const void* value,
    size_t size) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:bosdyn.api.LogAnnotationLogBlob.data)
}
inline std::string* LogAnnotationLogBlob::_internal_mutable_data() {
  
  return data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LogAnnotationLogBlob::release_data() {
  // @@protoc_insertion_point(field_release:bosdyn.api.LogAnnotationLogBlob.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogAnnotationLogBlob::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.LogAnnotationLogBlob.data)
}

// -------------------------------------------------------------------

// AddLogAnnotationResponse

// .bosdyn.api.ResponseHeader header = 1;
inline bool AddLogAnnotationResponse::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool AddLogAnnotationResponse::has_header() const {
  return _internal_has_header();
}
inline const ::bosdyn::api::ResponseHeader& AddLogAnnotationResponse::_internal_header() const {
  const ::bosdyn::api::ResponseHeader* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::bosdyn::api::ResponseHeader*>(
      &::bosdyn::api::_ResponseHeader_default_instance_);
}
inline const ::bosdyn::api::ResponseHeader& AddLogAnnotationResponse::header() const {
  // @@protoc_insertion_point(field_get:bosdyn.api.AddLogAnnotationResponse.header)
  return _internal_header();
}
inline void AddLogAnnotationResponse::unsafe_arena_set_allocated_header(
    ::bosdyn::api::ResponseHeader* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:bosdyn.api.AddLogAnnotationResponse.header)
}
inline ::bosdyn::api::ResponseHeader* AddLogAnnotationResponse::release_header() {
  
  ::bosdyn::api::ResponseHeader* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::bosdyn::api::ResponseHeader* AddLogAnnotationResponse::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:bosdyn.api.AddLogAnnotationResponse.header)
  
  ::bosdyn::api::ResponseHeader* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::bosdyn::api::ResponseHeader* AddLogAnnotationResponse::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::bosdyn::api::ResponseHeader>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::bosdyn::api::ResponseHeader* AddLogAnnotationResponse::mutable_header() {
  // @@protoc_insertion_point(field_mutable:bosdyn.api.AddLogAnnotationResponse.header)
  return _internal_mutable_header();
}
inline void AddLogAnnotationResponse::set_allocated_header(::bosdyn::api::ResponseHeader* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:bosdyn.api.AddLogAnnotationResponse.header)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace api
}  // namespace bosdyn

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::bosdyn::api::LogAnnotationTextMessage_Level> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bosdyn::api::LogAnnotationTextMessage_Level>() {
  return ::bosdyn::api::LogAnnotationTextMessage_Level_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_bosdyn_2fapi_2flog_5fannotation_2eproto
