// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: bosdyn/api/world_object_service.proto

#include "bosdyn/api/world_object_service.pb.h"
#include "bosdyn/api/world_object_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace bosdyn {
namespace api {

static const char* WorldObjectService_method_names[] = {
  "/bosdyn.api.WorldObjectService/ListWorldObjects",
  "/bosdyn.api.WorldObjectService/MutateWorldObjects",
};

std::unique_ptr< WorldObjectService::Stub> WorldObjectService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WorldObjectService::Stub> stub(new WorldObjectService::Stub(channel));
  return stub;
}

WorldObjectService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_ListWorldObjects_(WorldObjectService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_MutateWorldObjects_(WorldObjectService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WorldObjectService::Stub::ListWorldObjects(::grpc::ClientContext* context, const ::bosdyn::api::ListWorldObjectRequest& request, ::bosdyn::api::ListWorldObjectResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ListWorldObjects_, context, request, response);
}

void WorldObjectService::Stub::experimental_async::ListWorldObjects(::grpc::ClientContext* context, const ::bosdyn::api::ListWorldObjectRequest* request, ::bosdyn::api::ListWorldObjectResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ListWorldObjects_, context, request, response, std::move(f));
}

void WorldObjectService::Stub::experimental_async::ListWorldObjects(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::ListWorldObjectResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ListWorldObjects_, context, request, response, std::move(f));
}

void WorldObjectService::Stub::experimental_async::ListWorldObjects(::grpc::ClientContext* context, const ::bosdyn::api::ListWorldObjectRequest* request, ::bosdyn::api::ListWorldObjectResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ListWorldObjects_, context, request, response, reactor);
}

void WorldObjectService::Stub::experimental_async::ListWorldObjects(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::ListWorldObjectResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ListWorldObjects_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bosdyn::api::ListWorldObjectResponse>* WorldObjectService::Stub::AsyncListWorldObjectsRaw(::grpc::ClientContext* context, const ::bosdyn::api::ListWorldObjectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::bosdyn::api::ListWorldObjectResponse>::Create(channel_.get(), cq, rpcmethod_ListWorldObjects_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::bosdyn::api::ListWorldObjectResponse>* WorldObjectService::Stub::PrepareAsyncListWorldObjectsRaw(::grpc::ClientContext* context, const ::bosdyn::api::ListWorldObjectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::bosdyn::api::ListWorldObjectResponse>::Create(channel_.get(), cq, rpcmethod_ListWorldObjects_, context, request, false);
}

::grpc::Status WorldObjectService::Stub::MutateWorldObjects(::grpc::ClientContext* context, const ::bosdyn::api::MutateWorldObjectRequest& request, ::bosdyn::api::MutateWorldObjectResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_MutateWorldObjects_, context, request, response);
}

void WorldObjectService::Stub::experimental_async::MutateWorldObjects(::grpc::ClientContext* context, const ::bosdyn::api::MutateWorldObjectRequest* request, ::bosdyn::api::MutateWorldObjectResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_MutateWorldObjects_, context, request, response, std::move(f));
}

void WorldObjectService::Stub::experimental_async::MutateWorldObjects(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::MutateWorldObjectResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_MutateWorldObjects_, context, request, response, std::move(f));
}

void WorldObjectService::Stub::experimental_async::MutateWorldObjects(::grpc::ClientContext* context, const ::bosdyn::api::MutateWorldObjectRequest* request, ::bosdyn::api::MutateWorldObjectResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_MutateWorldObjects_, context, request, response, reactor);
}

void WorldObjectService::Stub::experimental_async::MutateWorldObjects(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::MutateWorldObjectResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_MutateWorldObjects_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bosdyn::api::MutateWorldObjectResponse>* WorldObjectService::Stub::AsyncMutateWorldObjectsRaw(::grpc::ClientContext* context, const ::bosdyn::api::MutateWorldObjectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::bosdyn::api::MutateWorldObjectResponse>::Create(channel_.get(), cq, rpcmethod_MutateWorldObjects_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::bosdyn::api::MutateWorldObjectResponse>* WorldObjectService::Stub::PrepareAsyncMutateWorldObjectsRaw(::grpc::ClientContext* context, const ::bosdyn::api::MutateWorldObjectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::bosdyn::api::MutateWorldObjectResponse>::Create(channel_.get(), cq, rpcmethod_MutateWorldObjects_, context, request, false);
}

WorldObjectService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorldObjectService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorldObjectService::Service, ::bosdyn::api::ListWorldObjectRequest, ::bosdyn::api::ListWorldObjectResponse>(
          [](WorldObjectService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bosdyn::api::ListWorldObjectRequest* req,
             ::bosdyn::api::ListWorldObjectResponse* resp) {
               return service->ListWorldObjects(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorldObjectService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorldObjectService::Service, ::bosdyn::api::MutateWorldObjectRequest, ::bosdyn::api::MutateWorldObjectResponse>(
          [](WorldObjectService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bosdyn::api::MutateWorldObjectRequest* req,
             ::bosdyn::api::MutateWorldObjectResponse* resp) {
               return service->MutateWorldObjects(ctx, req, resp);
             }, this)));
}

WorldObjectService::Service::~Service() {
}

::grpc::Status WorldObjectService::Service::ListWorldObjects(::grpc::ServerContext* context, const ::bosdyn::api::ListWorldObjectRequest* request, ::bosdyn::api::ListWorldObjectResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WorldObjectService::Service::MutateWorldObjects(::grpc::ServerContext* context, const ::bosdyn::api::MutateWorldObjectRequest* request, ::bosdyn::api::MutateWorldObjectResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace bosdyn
}  // namespace api

