// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: bosdyn/api/spot/spot_check_service.proto
// Original file comments:
// Copyright (c) 2020 Boston Dynamics, Inc.  All rights reserved.
//
// Downloading, reproducing, distributing or otherwise using the SDK Software
// is subject to the terms and conditions of the Boston Dynamics Software
// Development Kit License (20191101-BDSDK-SL).
//
#ifndef GRPC_bosdyn_2fapi_2fspot_2fspot_5fcheck_5fservice_2eproto__INCLUDED
#define GRPC_bosdyn_2fapi_2fspot_2fspot_5fcheck_5fservice_2eproto__INCLUDED

#include "bosdyn/api/spot/spot_check_service.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace bosdyn {
namespace api {
namespace spot {

// RPCs for monitoring robot health and recalibration various sensors. These procedures should be
// run periodically in order to keep the system running in the best possible condition.
class SpotCheckService final {
 public:
  static constexpr char const* service_full_name() {
    return "bosdyn.api.spot.SpotCheckService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Send a command to the SpotCheck service. The spotcheck service is responsible to both
    // recalibrating actuation sensors and checking camera health.
    virtual ::grpc::Status SpotCheckCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest& request, ::bosdyn::api::spot::SpotCheckCommandResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::SpotCheckCommandResponse>> AsyncSpotCheckCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::SpotCheckCommandResponse>>(AsyncSpotCheckCommandRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::SpotCheckCommandResponse>> PrepareAsyncSpotCheckCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::SpotCheckCommandResponse>>(PrepareAsyncSpotCheckCommandRaw(context, request, cq));
    }
    // Check the status of the spot check procedure. After procedure completes, this reports back
    // results for specific joints and cameras.
    virtual ::grpc::Status SpotCheckFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest& request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::SpotCheckFeedbackResponse>> AsyncSpotCheckFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::SpotCheckFeedbackResponse>>(AsyncSpotCheckFeedbackRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::SpotCheckFeedbackResponse>> PrepareAsyncSpotCheckFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::SpotCheckFeedbackResponse>>(PrepareAsyncSpotCheckFeedbackRaw(context, request, cq));
    }
    // Send a camera calibration command to the robot. Used to start or abort a calibration routine.
    virtual ::grpc::Status CameraCalibrationCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest& request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::CameraCalibrationCommandResponse>> AsyncCameraCalibrationCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::CameraCalibrationCommandResponse>>(AsyncCameraCalibrationCommandRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::CameraCalibrationCommandResponse>> PrepareAsyncCameraCalibrationCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::CameraCalibrationCommandResponse>>(PrepareAsyncCameraCalibrationCommandRaw(context, request, cq));
    }
    // Check the status of the camera calibration procedure.
    virtual ::grpc::Status CameraCalibrationFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest& request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>> AsyncCameraCalibrationFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>>(AsyncCameraCalibrationFeedbackRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>> PrepareAsyncCameraCalibrationFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>>(PrepareAsyncCameraCalibrationFeedbackRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Send a command to the SpotCheck service. The spotcheck service is responsible to both
      // recalibrating actuation sensors and checking camera health.
      virtual void SpotCheckCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest* request, ::bosdyn::api::spot::SpotCheckCommandResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SpotCheckCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::SpotCheckCommandResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SpotCheckCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest* request, ::bosdyn::api::spot::SpotCheckCommandResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SpotCheckCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest* request, ::bosdyn::api::spot::SpotCheckCommandResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SpotCheckCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::SpotCheckCommandResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SpotCheckCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::SpotCheckCommandResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Check the status of the spot check procedure. After procedure completes, this reports back
      // results for specific joints and cameras.
      virtual void SpotCheckFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SpotCheckFeedback(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SpotCheckFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SpotCheckFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SpotCheckFeedback(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SpotCheckFeedback(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Send a camera calibration command to the robot. Used to start or abort a calibration routine.
      virtual void CameraCalibrationCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CameraCalibrationCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void CameraCalibrationCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void CameraCalibrationCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void CameraCalibrationCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void CameraCalibrationCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Check the status of the camera calibration procedure.
      virtual void CameraCalibrationFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CameraCalibrationFeedback(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void CameraCalibrationFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void CameraCalibrationFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void CameraCalibrationFeedback(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void CameraCalibrationFeedback(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::SpotCheckCommandResponse>* AsyncSpotCheckCommandRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::SpotCheckCommandResponse>* PrepareAsyncSpotCheckCommandRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::SpotCheckFeedbackResponse>* AsyncSpotCheckFeedbackRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::SpotCheckFeedbackResponse>* PrepareAsyncSpotCheckFeedbackRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::CameraCalibrationCommandResponse>* AsyncCameraCalibrationCommandRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::CameraCalibrationCommandResponse>* PrepareAsyncCameraCalibrationCommandRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>* AsyncCameraCalibrationFeedbackRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>* PrepareAsyncCameraCalibrationFeedbackRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SpotCheckCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest& request, ::bosdyn::api::spot::SpotCheckCommandResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::SpotCheckCommandResponse>> AsyncSpotCheckCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::SpotCheckCommandResponse>>(AsyncSpotCheckCommandRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::SpotCheckCommandResponse>> PrepareAsyncSpotCheckCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::SpotCheckCommandResponse>>(PrepareAsyncSpotCheckCommandRaw(context, request, cq));
    }
    ::grpc::Status SpotCheckFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest& request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::SpotCheckFeedbackResponse>> AsyncSpotCheckFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::SpotCheckFeedbackResponse>>(AsyncSpotCheckFeedbackRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::SpotCheckFeedbackResponse>> PrepareAsyncSpotCheckFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::SpotCheckFeedbackResponse>>(PrepareAsyncSpotCheckFeedbackRaw(context, request, cq));
    }
    ::grpc::Status CameraCalibrationCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest& request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::CameraCalibrationCommandResponse>> AsyncCameraCalibrationCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::CameraCalibrationCommandResponse>>(AsyncCameraCalibrationCommandRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::CameraCalibrationCommandResponse>> PrepareAsyncCameraCalibrationCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::CameraCalibrationCommandResponse>>(PrepareAsyncCameraCalibrationCommandRaw(context, request, cq));
    }
    ::grpc::Status CameraCalibrationFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest& request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>> AsyncCameraCalibrationFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>>(AsyncCameraCalibrationFeedbackRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>> PrepareAsyncCameraCalibrationFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>>(PrepareAsyncCameraCalibrationFeedbackRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SpotCheckCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest* request, ::bosdyn::api::spot::SpotCheckCommandResponse* response, std::function<void(::grpc::Status)>) override;
      void SpotCheckCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::SpotCheckCommandResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SpotCheckCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest* request, ::bosdyn::api::spot::SpotCheckCommandResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SpotCheckCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest* request, ::bosdyn::api::spot::SpotCheckCommandResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SpotCheckCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::SpotCheckCommandResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SpotCheckCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::SpotCheckCommandResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void SpotCheckFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response, std::function<void(::grpc::Status)>) override;
      void SpotCheckFeedback(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SpotCheckFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SpotCheckFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SpotCheckFeedback(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SpotCheckFeedback(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void CameraCalibrationCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response, std::function<void(::grpc::Status)>) override;
      void CameraCalibrationCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void CameraCalibrationCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void CameraCalibrationCommand(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void CameraCalibrationCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void CameraCalibrationCommand(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void CameraCalibrationFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response, std::function<void(::grpc::Status)>) override;
      void CameraCalibrationFeedback(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void CameraCalibrationFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void CameraCalibrationFeedback(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void CameraCalibrationFeedback(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void CameraCalibrationFeedback(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::SpotCheckCommandResponse>* AsyncSpotCheckCommandRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::SpotCheckCommandResponse>* PrepareAsyncSpotCheckCommandRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::SpotCheckFeedbackResponse>* AsyncSpotCheckFeedbackRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::SpotCheckFeedbackResponse>* PrepareAsyncSpotCheckFeedbackRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::CameraCalibrationCommandResponse>* AsyncCameraCalibrationCommandRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::CameraCalibrationCommandResponse>* PrepareAsyncCameraCalibrationCommandRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>* AsyncCameraCalibrationFeedbackRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>* PrepareAsyncCameraCalibrationFeedbackRaw(::grpc::ClientContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SpotCheckCommand_;
    const ::grpc::internal::RpcMethod rpcmethod_SpotCheckFeedback_;
    const ::grpc::internal::RpcMethod rpcmethod_CameraCalibrationCommand_;
    const ::grpc::internal::RpcMethod rpcmethod_CameraCalibrationFeedback_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Send a command to the SpotCheck service. The spotcheck service is responsible to both
    // recalibrating actuation sensors and checking camera health.
    virtual ::grpc::Status SpotCheckCommand(::grpc::ServerContext* context, const ::bosdyn::api::spot::SpotCheckCommandRequest* request, ::bosdyn::api::spot::SpotCheckCommandResponse* response);
    // Check the status of the spot check procedure. After procedure completes, this reports back
    // results for specific joints and cameras.
    virtual ::grpc::Status SpotCheckFeedback(::grpc::ServerContext* context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response);
    // Send a camera calibration command to the robot. Used to start or abort a calibration routine.
    virtual ::grpc::Status CameraCalibrationCommand(::grpc::ServerContext* context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response);
    // Check the status of the camera calibration procedure.
    virtual ::grpc::Status CameraCalibrationFeedback(::grpc::ServerContext* context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SpotCheckCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SpotCheckCommand() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SpotCheckCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SpotCheckCommand(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckCommandRequest* /*request*/, ::bosdyn::api::spot::SpotCheckCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSpotCheckCommand(::grpc::ServerContext* context, ::bosdyn::api::spot::SpotCheckCommandRequest* request, ::grpc::ServerAsyncResponseWriter< ::bosdyn::api::spot::SpotCheckCommandResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SpotCheckFeedback : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SpotCheckFeedback() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SpotCheckFeedback() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SpotCheckFeedback(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* /*request*/, ::bosdyn::api::spot::SpotCheckFeedbackResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSpotCheckFeedback(::grpc::ServerContext* context, ::bosdyn::api::spot::SpotCheckFeedbackRequest* request, ::grpc::ServerAsyncResponseWriter< ::bosdyn::api::spot::SpotCheckFeedbackResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CameraCalibrationCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CameraCalibrationCommand() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_CameraCalibrationCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CameraCalibrationCommand(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCameraCalibrationCommand(::grpc::ServerContext* context, ::bosdyn::api::spot::CameraCalibrationCommandRequest* request, ::grpc::ServerAsyncResponseWriter< ::bosdyn::api::spot::CameraCalibrationCommandResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CameraCalibrationFeedback : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CameraCalibrationFeedback() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_CameraCalibrationFeedback() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CameraCalibrationFeedback(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCameraCalibrationFeedback(::grpc::ServerContext* context, ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* request, ::grpc::ServerAsyncResponseWriter< ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SpotCheckCommand<WithAsyncMethod_SpotCheckFeedback<WithAsyncMethod_CameraCalibrationCommand<WithAsyncMethod_CameraCalibrationFeedback<Service > > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SpotCheckCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_SpotCheckCommand() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::bosdyn::api::spot::SpotCheckCommandRequest, ::bosdyn::api::spot::SpotCheckCommandResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::bosdyn::api::spot::SpotCheckCommandRequest* request, ::bosdyn::api::spot::SpotCheckCommandResponse* response) { return this->SpotCheckCommand(context, request, response); }));}
    void SetMessageAllocatorFor_SpotCheckCommand(
        ::grpc::experimental::MessageAllocator< ::bosdyn::api::spot::SpotCheckCommandRequest, ::bosdyn::api::spot::SpotCheckCommandResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bosdyn::api::spot::SpotCheckCommandRequest, ::bosdyn::api::spot::SpotCheckCommandResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SpotCheckCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SpotCheckCommand(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckCommandRequest* /*request*/, ::bosdyn::api::spot::SpotCheckCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SpotCheckCommand(
      ::grpc::CallbackServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckCommandRequest* /*request*/, ::bosdyn::api::spot::SpotCheckCommandResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SpotCheckCommand(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckCommandRequest* /*request*/, ::bosdyn::api::spot::SpotCheckCommandResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SpotCheckFeedback : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_SpotCheckFeedback() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::bosdyn::api::spot::SpotCheckFeedbackRequest, ::bosdyn::api::spot::SpotCheckFeedbackResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* request, ::bosdyn::api::spot::SpotCheckFeedbackResponse* response) { return this->SpotCheckFeedback(context, request, response); }));}
    void SetMessageAllocatorFor_SpotCheckFeedback(
        ::grpc::experimental::MessageAllocator< ::bosdyn::api::spot::SpotCheckFeedbackRequest, ::bosdyn::api::spot::SpotCheckFeedbackResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bosdyn::api::spot::SpotCheckFeedbackRequest, ::bosdyn::api::spot::SpotCheckFeedbackResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SpotCheckFeedback() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SpotCheckFeedback(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* /*request*/, ::bosdyn::api::spot::SpotCheckFeedbackResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SpotCheckFeedback(
      ::grpc::CallbackServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* /*request*/, ::bosdyn::api::spot::SpotCheckFeedbackResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SpotCheckFeedback(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* /*request*/, ::bosdyn::api::spot::SpotCheckFeedbackResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_CameraCalibrationCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_CameraCalibrationCommand() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::bosdyn::api::spot::CameraCalibrationCommandRequest, ::bosdyn::api::spot::CameraCalibrationCommandResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* request, ::bosdyn::api::spot::CameraCalibrationCommandResponse* response) { return this->CameraCalibrationCommand(context, request, response); }));}
    void SetMessageAllocatorFor_CameraCalibrationCommand(
        ::grpc::experimental::MessageAllocator< ::bosdyn::api::spot::CameraCalibrationCommandRequest, ::bosdyn::api::spot::CameraCalibrationCommandResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(2);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bosdyn::api::spot::CameraCalibrationCommandRequest, ::bosdyn::api::spot::CameraCalibrationCommandResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_CameraCalibrationCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CameraCalibrationCommand(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* CameraCalibrationCommand(
      ::grpc::CallbackServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationCommandResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* CameraCalibrationCommand(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationCommandResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_CameraCalibrationFeedback : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_CameraCalibrationFeedback() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::bosdyn::api::spot::CameraCalibrationFeedbackRequest, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* request, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* response) { return this->CameraCalibrationFeedback(context, request, response); }));}
    void SetMessageAllocatorFor_CameraCalibrationFeedback(
        ::grpc::experimental::MessageAllocator< ::bosdyn::api::spot::CameraCalibrationFeedbackRequest, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(3);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bosdyn::api::spot::CameraCalibrationFeedbackRequest, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_CameraCalibrationFeedback() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CameraCalibrationFeedback(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* CameraCalibrationFeedback(
      ::grpc::CallbackServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* CameraCalibrationFeedback(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_SpotCheckCommand<ExperimentalWithCallbackMethod_SpotCheckFeedback<ExperimentalWithCallbackMethod_CameraCalibrationCommand<ExperimentalWithCallbackMethod_CameraCalibrationFeedback<Service > > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_SpotCheckCommand<ExperimentalWithCallbackMethod_SpotCheckFeedback<ExperimentalWithCallbackMethod_CameraCalibrationCommand<ExperimentalWithCallbackMethod_CameraCalibrationFeedback<Service > > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SpotCheckCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SpotCheckCommand() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SpotCheckCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SpotCheckCommand(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckCommandRequest* /*request*/, ::bosdyn::api::spot::SpotCheckCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SpotCheckFeedback : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SpotCheckFeedback() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SpotCheckFeedback() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SpotCheckFeedback(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* /*request*/, ::bosdyn::api::spot::SpotCheckFeedbackResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CameraCalibrationCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CameraCalibrationCommand() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_CameraCalibrationCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CameraCalibrationCommand(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CameraCalibrationFeedback : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CameraCalibrationFeedback() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_CameraCalibrationFeedback() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CameraCalibrationFeedback(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SpotCheckCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SpotCheckCommand() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SpotCheckCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SpotCheckCommand(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckCommandRequest* /*request*/, ::bosdyn::api::spot::SpotCheckCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSpotCheckCommand(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SpotCheckFeedback : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SpotCheckFeedback() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SpotCheckFeedback() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SpotCheckFeedback(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* /*request*/, ::bosdyn::api::spot::SpotCheckFeedbackResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSpotCheckFeedback(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CameraCalibrationCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CameraCalibrationCommand() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_CameraCalibrationCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CameraCalibrationCommand(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCameraCalibrationCommand(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CameraCalibrationFeedback : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CameraCalibrationFeedback() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_CameraCalibrationFeedback() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CameraCalibrationFeedback(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCameraCalibrationFeedback(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SpotCheckCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_SpotCheckCommand() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SpotCheckCommand(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_SpotCheckCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SpotCheckCommand(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckCommandRequest* /*request*/, ::bosdyn::api::spot::SpotCheckCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SpotCheckCommand(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SpotCheckCommand(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SpotCheckFeedback : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_SpotCheckFeedback() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SpotCheckFeedback(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_SpotCheckFeedback() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SpotCheckFeedback(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* /*request*/, ::bosdyn::api::spot::SpotCheckFeedbackResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SpotCheckFeedback(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SpotCheckFeedback(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_CameraCalibrationCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_CameraCalibrationCommand() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CameraCalibrationCommand(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_CameraCalibrationCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CameraCalibrationCommand(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* CameraCalibrationCommand(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* CameraCalibrationCommand(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_CameraCalibrationFeedback : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_CameraCalibrationFeedback() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CameraCalibrationFeedback(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_CameraCalibrationFeedback() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CameraCalibrationFeedback(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* CameraCalibrationFeedback(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* CameraCalibrationFeedback(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SpotCheckCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SpotCheckCommand() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bosdyn::api::spot::SpotCheckCommandRequest, ::bosdyn::api::spot::SpotCheckCommandResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bosdyn::api::spot::SpotCheckCommandRequest, ::bosdyn::api::spot::SpotCheckCommandResponse>* streamer) {
                       return this->StreamedSpotCheckCommand(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SpotCheckCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SpotCheckCommand(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckCommandRequest* /*request*/, ::bosdyn::api::spot::SpotCheckCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSpotCheckCommand(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bosdyn::api::spot::SpotCheckCommandRequest,::bosdyn::api::spot::SpotCheckCommandResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SpotCheckFeedback : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SpotCheckFeedback() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bosdyn::api::spot::SpotCheckFeedbackRequest, ::bosdyn::api::spot::SpotCheckFeedbackResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bosdyn::api::spot::SpotCheckFeedbackRequest, ::bosdyn::api::spot::SpotCheckFeedbackResponse>* streamer) {
                       return this->StreamedSpotCheckFeedback(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SpotCheckFeedback() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SpotCheckFeedback(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::SpotCheckFeedbackRequest* /*request*/, ::bosdyn::api::spot::SpotCheckFeedbackResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSpotCheckFeedback(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bosdyn::api::spot::SpotCheckFeedbackRequest,::bosdyn::api::spot::SpotCheckFeedbackResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CameraCalibrationCommand : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CameraCalibrationCommand() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bosdyn::api::spot::CameraCalibrationCommandRequest, ::bosdyn::api::spot::CameraCalibrationCommandResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bosdyn::api::spot::CameraCalibrationCommandRequest, ::bosdyn::api::spot::CameraCalibrationCommandResponse>* streamer) {
                       return this->StreamedCameraCalibrationCommand(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CameraCalibrationCommand() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CameraCalibrationCommand(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationCommandRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationCommandResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCameraCalibrationCommand(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bosdyn::api::spot::CameraCalibrationCommandRequest,::bosdyn::api::spot::CameraCalibrationCommandResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CameraCalibrationFeedback : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CameraCalibrationFeedback() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bosdyn::api::spot::CameraCalibrationFeedbackRequest, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bosdyn::api::spot::CameraCalibrationFeedbackRequest, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse>* streamer) {
                       return this->StreamedCameraCalibrationFeedback(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CameraCalibrationFeedback() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CameraCalibrationFeedback(::grpc::ServerContext* /*context*/, const ::bosdyn::api::spot::CameraCalibrationFeedbackRequest* /*request*/, ::bosdyn::api::spot::CameraCalibrationFeedbackResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCameraCalibrationFeedback(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bosdyn::api::spot::CameraCalibrationFeedbackRequest,::bosdyn::api::spot::CameraCalibrationFeedbackResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SpotCheckCommand<WithStreamedUnaryMethod_SpotCheckFeedback<WithStreamedUnaryMethod_CameraCalibrationCommand<WithStreamedUnaryMethod_CameraCalibrationFeedback<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SpotCheckCommand<WithStreamedUnaryMethod_SpotCheckFeedback<WithStreamedUnaryMethod_CameraCalibrationCommand<WithStreamedUnaryMethod_CameraCalibrationFeedback<Service > > > > StreamedService;
};

}  // namespace spot
}  // namespace api
}  // namespace bosdyn


#endif  // GRPC_bosdyn_2fapi_2fspot_2fspot_5fcheck_5fservice_2eproto__INCLUDED
